services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
